name: Send Teams Notification
description: 'Send a notification to Teams channel via Webhook.'

inputs:
  webhook_url:
    description: 'The webhook URL to send the notification to.'
    required: true
  information:
    description: 'Extended information.'
    default: ''
  ipa-link:
    description: 'The link to the ipa file.'
    required: false
  qr-link:
    description: 'The link to the ipa QR code.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Microsoft Teams Notification
      shell: bash
      run: |
        STATUS="${{ job.status }}"
        COLOR="good"

        if [[ "$STATUS" == "failure" ]]; then
          COLOR="attention"
        elif [[ "$STATUS" == "cancelled" ]]; then
          COLOR="warning"
        fi

        MESSAGE=$(cat <<EOF
        {
          "type": "message",
          "attachments": [
            {
              "contentType": "application/vnd.microsoft.card.adaptive",
              "content": {
                "\$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "version": "1.4",
                "type": "AdaptiveCard",
                "msteams": {
                  "width": "full"
                },
                "body": [
                  {
                    "type": "ColumnSet",
                    "columns": [
                      {
                        "type": "Column",
                        "width": "stretch",
                        "verticalContentAlignment": "center",
                        "items": [
                          {
                            "type": "TextBlock",
                            "size": "large",
                            "weight": "bolder",
                            "text": "ðŸ“± ${GITHUB_ACTOR} triggered a mobile app build"
                          }
                        ]
                      },
                      {
                        "type": "Column",
                        "width": "50px",
                        "items": [
                          {
                            "type": "Image",
                            "url": "https://raw.githubusercontent.com/Skitionek/notify-microsoft-teams/master/icons/${STATUS}.png",
                            "size": "stretch"
                          }
                        ]
                      }
                    ]
                  },
                  {
                    "type": "ColumnSet",
                    "columns": [
                      {
                        "type": "Column",
                        "width": "110px",
                        "verticalContentAlignment": "center",
                        "items": [
                          {
                            "type": "Image",
                            "url": "${{ inputs.qr-link }}",
                            "size": "stretch"
                          }
                        ]
                      },
                      {
                        "type": "Column",
                        "width": "stretch",
                        "verticalContentAlignment": "center",
                        "items": [
                          {
                            "type": "TextBlock",
                            "text": "**âœ… Status:** ${STATUS}",
                            "color": "good"
                          },
                          {
                            "type": "TextBlock",
                            "text": "**ðŸ—‚ï¸ Repository:** ${GITHUB_REPOSITORY}"
                          },
                          {
                            "type": "TextBlock",
                            "text": "**âš™ï¸ Environment:** ${{ inputs.information }}"
                          },
                          {
                            "type": "TextBlock",
                            "text": "**ðŸ·ï¸ Branch/Tag:** ${{ env.GH_REF_NAME }}"
                          }
                        ]
                      }
                    ]
                  },
                  {
                    "type": "ColumnSet",
                    "columns": [
                      {
                        "type": "Column",
                        "width": "stretch",
                        "items": [
                          {
                            "type": "ActionSet",
                            "actions": [
                              {
                                "type": "Action.OpenUrl",
                                "title": "View Workflow",
                                "url": "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
                              },
                              {
                                "type": "Action.OpenUrl",
                                "title": "Download .ipa file",
                                "url": "${{inputs.ipa-link}}"
                              }
                            ]
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            }
          ]
        }
        EOF
        )

        curl -H "Content-Type: application/json" --data-binary "$MESSAGE" "${{ inputs.webhook_url }}"