name: Generate JSON for Microsoft Teams Notification
description: "Action to combine the steps of multiple workflow jobs into one object for the notify-microsoft-teams action to consume"
inputs:
  needs-context:
    required: true
    description: "The context containing the jobs to combine"
outputs:
  job-context:
    description: "The job context to pass to the Microsoft Teams Notification action"
    value: ${{ steps.ms-teams-json.outputs.job-context }}
  steps-context:
    description: "The steps context to pass to the Microsoft Teams Notification action"
    value: ${{ steps.ms-teams-json.outputs.steps-context }}

runs:
  using: composite
  steps:
    - name: 📝 Generate MS Teams Notify JSON
      id: ms-teams-json
      shell: bash
      run: |
        declare -a steps_context_array=()
        for job in $(echo '${{ inputs.needs-context }}' | jq -c '.[]'); do
          job_status=$(echo "$job" | jq -r '.result')
          if [ $job_status == 'failure' ] || [ $job_status == 'cancelled' ]; then
            unsuccessful_status=$job_status
          fi
        
          steps_context=$(echo "$job" | jq -r '.outputs."steps-context"')
          if [ "$steps_context" != 'null' ]; then
            steps_context_array+=("$steps_context")
          fi
        done
        
        if [ "$unsuccessful_status" ]; then
          job_context=$(echo "{\"status\":\"${unsuccessful_status}\"}" | jq -c)
        else
          job_context=$(echo "{\"status\":\"success\"}" | jq -c)
        fi
        
        echo "job-context=$job_context" >> $GITHUB_OUTPUT
        echo "steps-context=$(jq -c -s 'reduce .[] as $item ({}; . * $item)' <<< "${steps_context_array[@]}")" >> $GITHUB_OUTPUT
