name: Generate Microsoft Teams Notify JSON
description: "Action to combine the steps of multiple workflow jobs into one object for the notify-microsoft-teams to consume"


runs:
  using: composite
  steps:
    - name: 📝 Generate MS Teams Notify JSON
      shell: bash
      run: |
        count=0
        mkdir steps
        
        for job in $(echo '${{ toJSON(needs) }}' | jq -c '.[]'); do
          job_status=$(echo "$job" | jq -r '.result')
          if [ $job_status == 'failure' ] || [ $job_status == 'cancelled' ]; then
            result=$job_status
          fi
        
          steps_context=$(echo "$job" | jq -r '.outputs.steps_context')
          if [ $steps_context != 'null' ]; then
            echo $steps_context > ./steps/job-${count}.json
          fi
        
          count=$((count + 1))
        done
        
        if [ $result ]; then
          job_context=$(echo "{\"status\":\"${result}\"}" | jq -c)
        else
          job_context=$(echo "{\"status\":\"success\"}" | jq -c)
        fi
        
        echo "job_context=$job_context" >> $GITHUB_OUTPUT
        echo "steps_context=$(jq -c -s 'reduce .[] as $item ({}; . * $item)' ./steps/*.json)" >> $GITHUB_OUTPUT
