name: Full DMS Deploy
description: "Action to run a full static load and related tasks when there are changes to the static task"

runs:
  using: composite
  steps:
    - name: 🚫 Disable Pollers and DMS Task Updater
      shell: bash
      run: |
        echo "Disabling Pollers and DMS Task Updater"

    - name: 🔄 Initialise TARS Replica
      shell: bash
      run: |
        echo "Initialising TARS Replica"

    - name: ⏳ DMS - Run Static Task Full Load
      shell: bash
      run: |
        echo "Running Static Full Load"

    - name: 🏃 Create & Run DMS Task Updater
      shell: bash
      run: |
        echo "Running DMS Task Updater"

    - name: ⏹️ Stop DMS Tasks
      shell: bash
      run: |
        echo "Stopping DMS Tasks"

    - name: ⏳ Load TARS Replica Database Objects
      shell: bash
      run: |
        echo "Loading TARS Replica Database Objects"

    - name: ▶️ Resume DMS Tasks
      shell: bash
      run: |
        echo "Resuming DMS Tasks"

    - name: 🏃 Run Journals Poller
      shell: bash
      run: |
        echo "Invoking Journals Poller"

    - name: ✅ Enable Pollers and DMS Task Updater
      shell: bash
      run: |
        echo "Enabling Pollers and DMS Task Updater"
