name: ⏹️ Stop DMS Task
description: "Action to stop the DMS task and to wait for the desired state"
inputs:
  task-arn:
    description: The ARN of the task to stop
    required: true
  timeout:
    description: How long to wait in seconds for the desired state
    required: false
    default: '300'
  interval:
    description: How often the to check whether the task is in the desired state
    required: false
    default: '10'
  aws-region:
    description: The AWS region to use
    required: true

runs:
  using: composite
  steps:
    - name: ⏹️ Stop DMS Tasks
      id: stop-dms-tasks
      shell: bash
      run: |
        status=$(aws dms describe-replication-tasks --without-settings --region ${{ inputs.aws-region }} \
        --query 'ReplicationTasks[?ReplicationTaskArn==`${{ inputs.task-arn }}`].Status' --output text)
        
        if [ "$status" != "stopped" ]; then
          aws dms stop-replication-task --region ${{ inputs.aws-region }} --replication-task-arn ${{ inputs.task-arn }} \
          --query 'ReplicationTask.Status'

        else
          echo "✅ The task is already stopped."
        fi
        
        echo "status=$status" >> $GITHUB_OUTPUT

    - name: ⏳ Wait for Task to Stop
      if: ${{ steps.stop-dms-tasks.outputs.status != 'stopped' }}
      shell: bash
      run: |
        elapsed=0
        
        until [ $(aws dms describe-replication-tasks --without-settings --region ${{ inputs.aws-region }} \
        --query 'ReplicationTasks[?ReplicationTaskArn==`${{ inputs.task-arn }}`].Status' --output text) == "stopped" ]; do
          if [ $elapsed -ge ${{ inputs.timeout }} ]; then
            echo "🚫 Timeout reached: Replication task did not become running within $((${{ inputs.timeout }} / 60)) minutes."
            exit 1
          fi
          
          echo "⏳ Waiting on the replication task to stop..."
          sleep ${{ inputs.interval }}
          elapsed=$((elapsed + ${{ inputs.interval }}))
        done
        
        echo "✅ The task has successfully stopped."
