name: Manage NonProd RDS Clusters
description: "Action to turn nonprod RDS clusters off or on"
inputs:
  cluster-name:
    required: true
    description: "The name of the cluster to turn off or on"
  aws-account-id:
    description: AWS MGMT Account ID
    required: true
  aws-nonprod-account-id:
    description: AWS NONPROD Account ID
    required: true
  aws-region:
    description: AWS Region
    required: true

runs:
  using: composite
  steps:
    - name: 🔑 Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/github-actions
        aws-region: ${{ inputs.aws-region }}

    - name: 🔑 Configure NonProd AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws-nonprod-account-id }}:role/github-actions
        aws-region: ${{ inputs.aws-region }}

    - name: echo cluster name
      shell: bash
      run : echo ${{ matrix.cluster-name }}
