name: Create PR list report

on: push
#on:
#  workflow_call:
#    secrets:
#      MSTEAMS_WEBHOOK:
#        required: true

jobs:
  create-pr-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test table
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPOS=(
            dvsa/mes-user-service
            dvsa/mes-logs-service
          )
          
          for repo in "${REPOS[@]}"; do
            LIST=$(gh pr list --repo $repo --json number,title,author --jq '.[]
              | select(.author.login | contains("snyk") or contains("dependabot"))
              | "https://github.com/$repo/pull/" + (.number) as $url 
              | [$url, .title]
              | @csv'
            )
          
          echo $LIST
          
          pull_number=$(echo "$LIST" | sed -E 's/.*\/([0-9]+),".*/\1/')
          title=$(echo "$LIST" | grep -oE ',".*"$' | tr -d '",')
          github_url="https://github.com/$repo/pull/$pull_number"

          {
            echo "### :rocket: Pr's"
            echo "| PR                  | Title    |"
            echo "| ------------------- | -------- |"
            echo "| $github_url         | $title   |"
          } >> $GITHUB_STEP_SUMMARY
          
          done

#      - name: 🔔 Microsoft Teams Notification
#        uses: skitionek/notify-microsoft-teams@v1.0.4
#        with:
#          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
#          raw: ${{ steps.prs.outputs.LIST }}
