name: 📦 Publish package

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        required: true
        type: string
      PACKAGE_NAME:
        required: true
        type: string
    secrets:
      NODE_AUTH_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read .nvmrc
        id: nvm
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Setup Node.js ${{ env.NVMRC }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NVMRC }}
          cache: 'npm'

      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=$ACCESS_TOKEN" >> ~/.npmrc
        env:
          ACCESS_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Test
        run: |
          npm run test --if-present
          npm run unit-test --if-present

      - name: Version bump check
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          PUBLISHED_VERSION=$(npm view ${{ inputs.PACKAGE_NAME }} version)
          
          if [ "$CURRENT_VERSION" = "$PUBLISHED_VERSION" ]; then
            echo "VERSION_BUMPED=false" >> $GITHUB_ENV
          else
            echo "VERSION_BUMPED=true" >> $GITHUB_ENV
          fi

      - name: Publish
        if: ${{ env.VERSION_BUMPED == 'true' }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
