name: 📑 Terraform Plan/Apply

on:
  workflow_call:
    inputs:
      runner:
        description: The EC2 GHA runner that has been spun up for deployment
        type: string
        required: false
        default: ubuntu-latest
      branch:
        description: Terraform Branch
        type: string
        required: true
      aws-account:
        description: AWS Account
        type: string
        required: true
      tf-environment:
        description: Terraform Environment
        type: string
        required: true
      tf-component:
        description: Terraform Component
        type: string
        required: true
      release-tag:
        description: The release tag to run a Terraform plan against (optional)
        type: string
        required: false
      tf-args:
        description: Additional Terraform arguments (optional)
        type: string
        required: false
      tf-action:
        description: The Terraform action to perform (plan/apply)
        type: string
        required: true
        default: plan
      artifact-name-prefix:
        description: The prefix to add to the Terraform plan artifact if DRS early run takes place
        type: string
        required: false

permissions:
  id-token: write
  contents: write

jobs:
  tf-action:
    name: "${{ inputs.tf-action == 'plan' && '📑 Plan' || '' }}${{ inputs.tf-action == 'apply' && '🚀 Apply' || '' }}${{ inputs.tf-action == 'destroy' && '🗑️ Destroy' || '' }} ${{ inputs.tf-component }}"
    runs-on: ${{ inputs.runner }}
    environment: ${{ contains(fromJSON('["apply", "destroy"]'), inputs.tf-action) && inputs.tf-environment || '' }}
    steps:
      - name: 📨 Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: 🔑 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_MGMT }}
          aws-region: ${{ secrets.DVSA_AWS_REGION }}
          role-session-name: Terraform-GHA

      - name: 🤫 Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: des-globals/env
          parse-json-secrets: true

      - name: ✍️ Generate tfvars
        id: get-tfvars
        if: ${{ contains(fromJSON('["dev", "uat", "perf", "prep", "live"]'), inputs.tf-environment) && inputs.tf-component != 'dmsbase' }}
        uses: dvsa/des-workflow-actions/.github/actions/get-tfvars@main
        with:
          environment: ${{ inputs.tf-environment }}
          component: ${{ inputs.tf-component }}
          release-tag: ${{ inputs.release-tag }}

      - name: 🔑 Assume AWS ${{ inputs.aws-account }} Role
        if: inputs.aws-account != 'mgmt'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-account == 'prod' && secrets.AWS_ROLE_PROD || secrets.AWS_ROLE_NONPROD }}
          aws-region: ${{ secrets.DVSA_AWS_REGION }}
          role-session-name: Terraform-GHA

      - name: 🔍 Get Terraform Version
        shell: bash
        run: echo "TF_VERSION=$(cat components/${{ inputs.tf-component }}/.terraform-version)" >> $GITHUB_ENV

      - name: ⚙️ Configure Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: ${{ inputs.tf-action == 'plan' && '📝 Terraform Plan' || '' }}${{ inputs.tf-action == 'apply' && '🚀 Terraform Apply' || '' }}${{ inputs.tf-action == 'destroy' && '🗑️ Terraform Destroy' || '' }}
        run: |
          bash -x bin/terraform.sh \
          --action ${{ inputs.tf-action }} \
          --project mes \
          --environment ${{ inputs.tf-environment }} \
          --component ${{ inputs.tf-component }} \
          --group ${{ inputs.aws-account }} \
          --bucket-prefix dvsa.mes.tf \
          --region ${{ secrets.DVSA_AWS_REGION }} \
          -- ${{ steps.get-tfvars.outputs.tfvars }} \
          ${{ inputs.tf-args }} \
          ${{ inputs.tf-action == 'plan' && '-out=tfplan' || '' }}

      - name: 🧐 Terraform Show
        if: ${{ inputs.tf-action == 'plan' }}
        run: |
          # Set Filename        
          filename="${{ inputs.tf-environment }}-${{ inputs.tf-component }}-plan.txt"
          
          # Prepend artifact-name-prefix to the filename to avoid duplicate files when DRS component early run takes place
          [[ -n "${{ inputs.artifact-name-prefix }}" ]] && filename="${{ inputs.artifact-name-prefix }}_$filename"
          
          echo "FILE_NAME=$filename" >> $GITHUB_ENV
          
          terraform init components/${{ inputs.tf-component }}
          terraform show -no-color components/${{ inputs.tf-component }}/tfplan > ${{ github.workspace }}/$filename

      - name: ☁️ Upload Plan
        if: ${{ inputs.tf-action == 'plan' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE_NAME }}
          path: ${{ env.FILE_NAME }}
          retention-days: 3
